### ISSUE TITLE
Blackboard Enhancement Suite for NAU

### ISSUE THREAD

**Issue by Monkolf** [dcrousso/BlackboardEnhancementSuite#1]
Please make the Blackboard Enhancement Suite extension for Northern Arizona University!!

**Comment by dcrousso** [comment]
Can you provide me with the URL for the homepage for NAU's blackboard?  Like USC's is https://blackboard.usc.edu/webapps/portal/frameset.jsp.  Thanks!

**Comment by snydergd** [comment]
Could the extension be made to work on all bb.*.edu/\* and blackboard.*.edu/\* urls?  [UIS](http://uis.edu/) has its blackboard at bb.uis.edu.  More than likely any URL matching those patterns will be a blackboard system for a university or college somewhere.

**Comment by dcrousso** [comment]
Hey @snydergd thanks for the request.  I just merged your changes in #2 and have pushed the new code to the [store](https://chrome.google.com/webstore/detail/mbmniljdacmobchkdodbbimnnfemgjda/).  Please let me know if it doesn't work or if any other issues arise (or feel free to make more pull requests).
